version: '3'
services:
  db:
   image: postgres
   environment:
    POSTGRES_HOST_AUTH_METHOD: 'trust' 
  web_backend:
   container_name: web_backend_new_project
   build:
    context: ./backend/.
    dockerfile: DockerfileDjango
   tty: true 
   command: django-admin.py startproject new_dj .
   volumes:
    - ./backend:/code
   ports:
    - "8000:8000"
   depends_on:
    - db   
  web_frontend:
   container_name: web_frontend_new_project
   build:
    context: ./frontend/.
    dockerfile: DockerfileReact
   tty: true 
   command:  "yarn start"
   volumes:
    - ./frontend:/code
   ports:
    - "3000:3000"
   depends_on:
    - web_backend